photo-sorter:
  source-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2026\\2026-07-03 21-15-50"
  destination-folder: "C:\\Users\\npitt\\Downloads\\匯出照片\\iCareFone\\Photo\\2026\\2026-07-03 21-15-50\\Sorted"
